/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: ['class', 'class'],
  content: ['./index.html', './src/**/*.{js,jsx,ts,tsx}'],
  theme: {
    extend: {
      colors: {
        brand: {
          50: '#eef2ff',
          100: '#e0e7ff',
          200: '#c7d2fe',
          300: '#a5b4fc',
          400: '#818cf8',
          500: '#6366f1',
          600: '#4f46e5',
          700: '#4338ca',
          800: '#3730a3',
          900: '#312e81',
          DEFAULT: '#4f46e5',
        },
        bab: {
          100: '#fff2ee',
          200: '#ffcbbb',
          300: '#ffa588',
          400: '#ff7e55',
          500: '#FF5722',
          600: '#ee3900',
          700: '#bb2d00',
          800: '#882100',
          900: '#551400',
          DEFAULT: '#FF5722',
        },
        babgray: {
          100: '#F5F5F5',
          150: '#E5E7EB',
          200: '#DBDBDB',
          300: '#C2C2C2',
          400: '#A8A8A8',
          500: '#8F8F8F',
          600: '#757575',
          700: '#5C5C5C',
          800: '#424242',
          900: '#292929',
          DEFAULT: '#E5E7EB',
        },
        babbutton: {
          red: '#EF4444',
          red_back: '#FEE2E2',
          blue: '#3B82F6',
          blue_back: '#DBEAFE',
          green: '#22C55E',
          green_back: '#DCFCE7',
          purple: '#A855F7',
          purple_back: '#F3E8FF',
          brown: '#C2481F',
          brown_back: '#FFEDD5',
          black: '#374151',
          black_back: '#F3F4F6',
          yellow: '#FACC15',
          yellow_back: '#FEF9C3',
        },
        babcategory: {
          koreanbg: '#FFF3E0',
          koreantext: '#5D4037',
          chinesebg: '#FFEBEE',
          chinesetext: '#B71C1C',
          japanesbg: '#E8EAF6',
          japanestext: '#303F9F',
          italianbg: '#F1F8E9',
          italiantext: '#33691E',
          kfoodbg: '#FFFDE7',
          kfoodtext: '#827717',
          asianbg: '#F3E5F5',
          asiantext: '#6A1B9A',
          indianbg: '#DBEAFE',
          indiantext: '#1E40AF',
          mexicanbg: '#E1F5FE',
          mexicantext: '#0277BD',
          cafebg: '#EFEBE9',
          cafetext: '#4E342E',
          dessertbg: '#FFF8E1',
          desserttext: '#6D4C41',
          alcoholbg: '#FCE4EC',
          alcoholtext: '#880E4F',
          indoorbg: '#FCE4EC',
          indoortext: '#AD1457',
          outdoorbg: '#F9FBE7',
          outdoortext: '#616161',
          rooftopbg: '#E3F2FD',
          rooftoptext: '#1565C0',
        },
        bg: {
          bg: '#F9FAFB',
        },
        bgs: 'hsl(var(--bg))',
        fg: 'hsl(var(--fg))',
        surface: 'hsl(var(--surface))',
        borderc: 'hsl(var(--border))',
        primary: {
          DEFAULT: 'hsl(var(--primary))',
          foreground: 'hsl(var(--primary-foreground))',
        },
        'primary-fg': 'hsl(var(--primary-fg))',
        background: 'hsl(var(--background))',
        foreground: 'hsl(var(--foreground))',
        card: {
          DEFAULT: 'hsl(var(--card))',
          foreground: 'hsl(var(--card-foreground))',
        },
        popover: {
          DEFAULT: 'hsl(var(--popover))',
          foreground: 'hsl(var(--popover-foreground))',
        },
        secondary: {
          DEFAULT: 'hsl(var(--secondary))',
          foreground: 'hsl(var(--secondary-foreground))',
        },
        muted: {
          DEFAULT: 'hsl(var(--muted))',
          foreground: 'hsl(var(--muted-foreground))',
        },
        accent: {
          DEFAULT: 'hsl(var(--accent))',
          foreground: 'hsl(var(--accent-foreground))',
        },
        destructive: {
          DEFAULT: 'hsl(var(--destructive))',
          foreground: 'hsl(var(--destructive-foreground))',
        },
        border: 'hsl(var(--border))',
        input: 'hsl(var(--input))',
        ring: 'hsl(var(--ring))',
        chart: {
          1: 'hsl(var(--chart-1))',
          2: 'hsl(var(--chart-2))',
          3: 'hsl(var(--chart-3))',
          4: 'hsl(var(--chart-4))',
          5: 'hsl(var(--chart-5))',
        },
      },
      boxShadow: {
        card: '0 2px 10px rgba(0,0,0,0.08)',
      },
      borderRadius: {
        xl2: '1rem',
        lg: 'var(--radius)',
        md: 'calc(var(--radius) - 2px)',
        sm: 'calc(var(--radius) - 4px)',
      },
    },
  },
  plugins: [require('tailwindcss-animate')],
};
